// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vtb_vga_uart.cpp"
#include "Vtb_vga_uart___024root__DepSet_hcf22b48e__0.cpp"
#include "Vtb_vga_uart___024root__DepSet_h0bd5067b__0.cpp"
#include "Vtb_vga_uart__main.cpp"
#include "Vtb_vga_uart__Trace__0.cpp"
#include "Vtb_vga_uart___024root__Slow.cpp"
#include "Vtb_vga_uart___024root__DepSet_hcf22b48e__0__Slow.cpp"
#include "Vtb_vga_uart___024root__DepSet_h0bd5067b__0__Slow.cpp"
#include "Vtb_vga_uart__Syms.cpp"
#include "Vtb_vga_uart__Trace__0__Slow.cpp"
#include "Vtb_vga_uart__TraceDecls__0__Slow.cpp"
